apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rwo-test
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
    - name: volume-test
      image: nginx:stable-alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: volv
          mountPath: /data
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
  volumes:
    - name: volv
      persistentVolumeClaim:
        claimName: rwo-test
